"""Round-trip tests for tools/validate_against_capture.py.

There is no real camera on CI, so captures are generated by the simulator
(apply_emva_noise.py) from a recipe and analysed back. A matching recipe must
reproduce its own parameters; a deliberately wrong recipe must be flagged.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

import numpy as np
import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))

import validate_against_capture as vac  # noqa: E402
from camera_model import load_camera_model  # noqa: E402

RECIPE = REPO / "config" / "camera_recipes" / "default.yaml"


class TestRawHelpers(unittest.TestCase):
    def test_cfa_offsets_gbrg(self):
        off = vac.cfa_offsets("GBRG")
        self.assertEqual(off["G"], [(0, 0), (1, 1)])
        self.assertEqual(off["B"], [(0, 1)])
        self.assertEqual(off["R"], [(1, 0)])

    def test_raw16_round_trip(self):
        with tempfile.TemporaryDirectory() as tmp:
            a = np.arange(12, dtype="<u2").reshape(3, 4)
            a.tofile(Path(tmp) / "x.raw16")
            b, _ = vac.read_raw(Path(tmp) / "x.raw16", {"format": "raw16", "height": 3, "width": 4})
            np.testing.assert_array_equal(a, b)

    def test_crop_keeps_cfa_phase(self):
        img = np.arange(100.0).reshape(10, 10)
        self.assertEqual(vac.crop(img, [3, 5, 9, 9])[0, 0], img[4, 2])

    def test_grid_patch_rois_are_row_major(self):
        rois = vac.patch_rois({"grid": vac.chart_grid_cfg(24)})
        self.assertEqual(len(rois), 24)
        self.assertLess(rois[0][0], rois[5][0])
        self.assertLess(rois[0][1], rois[6][1])


class TestEmvaAnalysis(unittest.TestCase):
    """analyse_emva on emva_theory stacks with known parameters (no subprocess)."""

    def test_recovers_known_parameters(self):
        rec = vac.recipe_emva(load_camera_model(RECIPE))
        rec.update(prnu_fraction=0.02, dsnu_e=3.0, dark_current_e_per_s=20.0)
        shape = (16, 96, 96)
        darks = [(t, np.zeros(shape)) for t in (0.01, 2.0, 8.0)]
        flats = [(0.01, f, np.zeros(shape)) for f in vac.FLAT_FRACTIONS]
        ptc = [
            {"mu_dn": f * rec["full_well_e"] / rec["K_e_per_DN"], "var_dn2": f, "relative_exposure": f}
            for f in vac.FLAT_FRACTIONS
        ]
        sd, sf = vac.simulate_emva_captures(rec, darks, flats, {"ptc": ptc}, seed=3)
        m = vac.analyse_emva(sd, sf)
        self.assertAlmostEqual(m["K_e_per_DN"] / rec["K_e_per_DN"], 1.0, delta=0.05)
        self.assertAlmostEqual(m["read_noise_e"] / rec["read_noise_e"], 1.0, delta=0.05)
        self.assertAlmostEqual(m["prnu_fraction"] / 0.02, 1.0, delta=0.1)
        self.assertAlmostEqual(m["dsnu_e"] / 3.0, 1.0, delta=0.15)
        self.assertAlmostEqual(m["dark_current_e_per_s"] / 20.0, 1.0, delta=0.05)
        self.assertTrue(m["saturation_reached"])
        self.assertAlmostEqual(m["full_well_e"] / rec["full_well_e"], 1.0, delta=0.1)


class TestRoundTrip(unittest.TestCase):
    """Simulator -> captures -> harness, matched and mismatched recipes."""

    @classmethod
    def setUpClass(cls):
        cls.tmp = tempfile.TemporaryDirectory()
        root = Path(cls.tmp.name)
        cls.capture = vac.synthesize(RECIPE, root / "cap", frames=3, edge_extra_blur_px=1.0, seed=5)
        cls.report = vac.validate(cls.capture, root / "rep")
        model = load_camera_model(RECIPE)
        model.pop("resolved_from", None)
        model["noise"]["emva"]["overall_system_gain_K_e_per_DN"] *= 1.25
        model["noise"]["emva"]["sigma_d_e"] *= 2.0
        q = model["sensor"]["quantum_efficiency"]
        q["red_csv"], q["blue_csv"] = q["blue_csv"], q["red_csv"]
        cls.wrong = root / "wrong.yaml"
        cls.wrong.write_text(yaml.safe_dump(model))
        cls.wrong_report = vac.validate(cls.capture, root / "rep_wrong", recipe_override=cls.wrong)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def test_matching_recipe_reproduces_emva_parameters(self):
        p = self.report["emva"]["parameters"]
        for key, tol in (("K_e_per_DN", 6), ("read_noise_e", 8), ("dark_current_e_per_s", 15), ("full_well_e", 6)):
            self.assertLess(abs(p[key]["measured_vs_simulated_pct"]), tol, msg=f"{key}: {p[key]}")
        self.assertLess(abs(p["K_e_per_DN"]["measured_vs_recipe_pct"]), 6)
        self.assertLess(abs(p["black_level_DN"]["measured_vs_recipe_pct"]), 1)

    def test_matching_recipe_reproduces_colorchecker(self):
        c = self.report["colorchecker"]
        self.assertLess(c["delta_e_2000_mean"], 1.5)
        self.assertLess(c["rms_white_normalised_error_pct"], 3.0)

    def test_extra_lens_blur_is_detected_as_lower_measured_mtf(self):
        e = self.report["slanted_edge"]
        self.assertAlmostEqual(e["measured"]["angle_deg"], 5.0, delta=0.15)
        self.assertLess(e["mtf50_measured_vs_simulated_pct"], -15.0)

    def test_wrong_recipe_is_flagged(self):
        p = self.wrong_report["emva"]["parameters"]
        self.assertLess(p["K_e_per_DN"]["measured_vs_recipe_pct"], -15)
        self.assertLess(p["read_noise_e"]["measured_vs_recipe_pct"], -35)
        self.assertGreater(self.wrong_report["colorchecker"]["delta_e_2000_mean"], 5.0)

    def test_refit_model_loads_and_carries_measured_values(self):
        model = vac.refit_model(load_camera_model(RECIPE), self.report, RECIPE)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "refit.yaml"
            path.write_text(yaml.safe_dump(model))
            loaded = load_camera_model(path)
        k = self.report["emva"]["measured"]["K_e_per_DN"]
        self.assertAlmostEqual(loaded["noise"]["emva"]["overall_system_gain_K_e_per_DN"], k)


if __name__ == "__main__":
    unittest.main()
