#!/usr/bin/env python3
"""Generate PBRT scenes for common image-quality targets.

Targets:
- slanted_edge: high-contrast slanted edge for MTF estimation.
- iso_noise: grayscale patch array for noise/SNR sweeps.
- siemens_star: radial spokes for MTF/aliasing visualization.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path

LEGACY_REALISTIC_LENSFILE = "scenes/lenses/wide_22mm.dat"
DEFAULT_REALISTIC_LENSFILE = "config/lenses/wide_22mm.dat"


def resolve_lensfile(repo: Path, lensfile_rel: str) -> Path:
    lens_path = (repo / lensfile_rel).resolve()
    if lens_path.is_file():
        return lens_path
    if lensfile_rel == LEGACY_REALISTIC_LENSFILE:
        migrated = (repo / DEFAULT_REALISTIC_LENSFILE).resolve()
        if migrated.is_file():
            return migrated
    return lens_path


def _camera_block(args: argparse.Namespace, scene_dir: Path, repo: Path) -> list[str]:
    focus_d = float(args.focus_distance) if args.focus_distance is not None else float(args.cam_dist)
    if args.camera in ("perspective", "pinhole"):
        return [f'Camera "perspective" "float fov" [{float(args.fov):.6g}]']
    if args.camera == "thinlens":
        thin_focus = (
            float(args.thinlens_focal_distance)
            if args.thinlens_focal_distance is not None
            else float(args.cam_dist)
        )
        return [
            'Camera "perspective"',
            f'    "float fov" [{float(args.fov):.6g}]',
            f'    "float lensradius" [{float(args.thinlens_lens_radius):.6g}]',
            f'    "float focaldistance" [{thin_focus:.6g}]',
        ]

    lens_repo = resolve_lensfile(repo, args.lensfile)
    if not lens_repo.is_file():
        raise FileNotFoundError(f"realistic camera: lens file not found: {lens_repo}")
    lens_for_scene = os.path.relpath(str(lens_repo), str(scene_dir.resolve()))
    return [
        'Camera "realistic"',
        f'    "string lensfile" ["{lens_for_scene}"]',
        f'    "float aperturediameter" [{float(args.aperture_diameter_mm):.6g}]',
        f'    "float focusdistance" [{focus_d:.6g}]',
    ]


def _film_block(args: argparse.Namespace, film_output: str) -> list[str]:
    film = str(args.film).lower()
    if film == "rgb":
        return [
            'Film "rgb"',
            f'    "string filename" ["{film_output}"]',
            f'    "integer xresolution" [{int(args.xres)}]',
            f'    "integer yresolution" [{int(args.yres)}]',
            '    "bool savefp16" false',
            '    "float iso" [100]',
        ]
    return [
        'Film "spectral"',
        f'    "string filename" ["{film_output}"]',
        f'    "integer xresolution" [{int(args.xres)}]',
        f'    "integer yresolution" [{int(args.yres)}]',
        '    "bool savefp16" false',
        f'    "integer nbuckets" [{int(args.spectral_nbuckets)}]',
        f'    "float lambdamin" [{float(args.spectral_lambda_min):.6g}]',
        f'    "float lambdamax" [{float(args.spectral_lambda_max):.6g}]',
    ]


def _scene_header(args: argparse.Namespace, scene_dir: Path, repo: Path, film_output: str, label: str) -> list[str]:
    return [
        f"# Generated by tools/build_image_quality_targets.py ({label})",
        'Option "disablepixeljitter" false',
        'Option "seed" 0',
        "",
        'ColorSpace "srgb"',
        "",
        f'Sampler "zsobol" "integer pixelsamples" [{int(args.pixelsamples)}]',
        'Integrator "path" "integer maxdepth" [8]',
        'PixelFilter "gaussian"',
        "",
        *_film_block(args, film_output),
        "",
        "LookAt",
        f"0 0 {float(args.cam_dist):.6f}",
        "    0 0 0",
        "    0 1 0",
        *_camera_block(args, scene_dir, repo),
        "",
        "WorldBegin",
        "",
        'LightSource "distant"',
        f'    "rgb L" [{float(args.light_scale):.6g} {float(args.light_scale):.6g} {float(args.light_scale):.6g}]',
        '    "point3 from" [0.0 0.0 3.0]',
        '    "point3 to" [0.0 0.0 0.0]',
        "",
    ]


def _background_plane(width: float, height: float, refl: float = 0.18) -> list[str]:
    hw = width / 2.0
    hh = height / 2.0
    return [
        "AttributeBegin",
        f'    Material "diffuse" "rgb reflectance" [{refl:.6g} {refl:.6g} {refl:.6g}]',
        '    Shape "bilinearmesh"',
        f'        "point3 P" [ {-hw:.6g} {-hh:.6g} 0.0   {hw:.6g} {-hh:.6g} 0.0   {-hw:.6g} {hh:.6g} 0.0   {hw:.6g} {hh:.6g} 0.0 ]',
        '        "point2 uv" [ 0 0   1 0   0 1   1 1 ]',
        "AttributeEnd",
        "",
    ]


def build_slanted_edge_lines(width: float, height: float, angle_deg: float, edge_offset: float) -> list[str]:
    lines = _background_plane(width, height, refl=0.04)
    edge_h = height * 1.3
    edge_w = width * 0.7
    cx = edge_offset
    cy = 0.0
    rad = math.radians(angle_deg)
    c = math.cos(rad)
    s = math.sin(rad)
    local = [(-edge_w / 2.0, -edge_h / 2.0), (edge_w / 2.0, -edge_h / 2.0), (-edge_w / 2.0, edge_h / 2.0), (edge_w / 2.0, edge_h / 2.0)]
    pts = []
    for x, y in local:
        xr = c * x - s * y + cx
        yr = s * x + c * y + cy
        pts.append((xr, yr, 0.001))
    lines.extend(
        [
            "# Bright plate over dark background creates a slanted high-contrast edge.",
            "AttributeBegin",
            '    Material "diffuse" "rgb reflectance" [0.95 0.95 0.95]',
            '    Shape "bilinearmesh"',
            '        "point3 P" [ '
            f"{pts[0][0]:.6g} {pts[0][1]:.6g} {pts[0][2]:.6g}   "
            f"{pts[1][0]:.6g} {pts[1][1]:.6g} {pts[1][2]:.6g}   "
            f"{pts[2][0]:.6g} {pts[2][1]:.6g} {pts[2][2]:.6g}   "
            f"{pts[3][0]:.6g} {pts[3][1]:.6g} {pts[3][2]:.6g} ]",
            '        "point2 uv" [ 0 0   1 0   0 1   1 1 ]',
            "AttributeEnd",
            "",
        ]
    )
    return lines


def build_iso_noise_lines(width: float, height: float, rows: int, cols: int, min_reflectance: float, max_reflectance: float) -> list[str]:
    lines = _background_plane(width, height, refl=0.2)
    margin_x = width * 0.06
    margin_y = height * 0.08
    gap_x = width * 0.02
    gap_y = height * 0.03
    patch_w = (width - 2 * margin_x - (cols - 1) * gap_x) / cols
    patch_h = (height - 2 * margin_y - (rows - 1) * gap_y) / rows
    x0 = -width / 2.0 + margin_x
    y_top = height / 2.0 - margin_y
    total = rows * cols
    for r in range(rows):
        for c in range(cols):
            idx = r * cols + c
            t = idx / (total - 1) if total > 1 else 0.0
            refl = min_reflectance * (1.0 - t) + max_reflectance * t
            xl = x0 + c * (patch_w + gap_x)
            xr = xl + patch_w
            yt = y_top - r * (patch_h + gap_y)
            yb = yt - patch_h
            lines.extend(
                [
                    "AttributeBegin",
                    f'    Material "diffuse" "rgb reflectance" [{refl:.6g} {refl:.6g} {refl:.6g}]',
                    '    Shape "bilinearmesh"',
                    f'        "point3 P" [ {xl:.6g} {yb:.6g} 0.001   {xr:.6g} {yb:.6g} 0.001   {xl:.6g} {yt:.6g} 0.001   {xr:.6g} {yt:.6g} 0.001 ]',
                    '        "point2 uv" [ 0 0   1 0   0 1   1 1 ]',
                    "AttributeEnd",
                    "",
                ]
            )
    return lines


def build_siemens_star_lines(width: float, height: float, spokes: int, radius_fraction: float) -> list[str]:
    lines = _background_plane(width, height, refl=0.5)
    r = min(width, height) * 0.5 * radius_fraction
    z = 0.001
    for i in range(spokes):
        t0 = 2.0 * math.pi * i / spokes
        t1 = 2.0 * math.pi * (i + 1) / spokes
        x0 = r * math.cos(t0)
        y0 = r * math.sin(t0)
        x1 = r * math.cos(t1)
        y1 = r * math.sin(t1)
        refl = 0.05 if i % 2 == 0 else 0.95
        lines.extend(
            [
                "AttributeBegin",
                f'    Material "diffuse" "rgb reflectance" [{refl:.6g} {refl:.6g} {refl:.6g}]',
                '    Shape "trianglemesh"',
                '        "integer indices" [ 0 1 2 ]',
                f'        "point3 P" [ 0 0 {z:.6g}   {x0:.6g} {y0:.6g} {z:.6g}   {x1:.6g} {y1:.6g} {z:.6g} ]',
                "AttributeEnd",
                "",
            ]
        )
    return lines


def write_target_scene(args: argparse.Namespace, repo: Path, out_dir: Path, target: str) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    scene_path = out_dir / f"{target}.pbrt"
    film_output = f"out/{target}_{str(args.film).lower()}.exr"
    lines = _scene_header(args, out_dir, repo, film_output, target)
    if target == "slanted_edge":
        lines.extend(
            build_slanted_edge_lines(
                width=float(args.target_width),
                height=float(args.target_height),
                angle_deg=float(args.slanted_angle_deg),
                edge_offset=float(args.slanted_edge_offset),
            )
        )
    elif target == "iso_noise":
        lines.extend(
            build_iso_noise_lines(
                width=float(args.target_width),
                height=float(args.target_height),
                rows=int(args.iso_rows),
                cols=int(args.iso_cols),
                min_reflectance=float(args.iso_min_reflectance),
                max_reflectance=float(args.iso_max_reflectance),
            )
        )
    elif target == "siemens_star":
        lines.extend(
            build_siemens_star_lines(
                width=float(args.target_width),
                height=float(args.target_height),
                spokes=int(args.siemens_spokes),
                radius_fraction=float(args.siemens_radius_fraction),
            )
        )
    else:
        raise ValueError(f"unsupported target: {target}")
    scene_path.write_text("\n".join(lines) + "\n")
    return {
        "target": target,
        "scene": str(scene_path.relative_to(repo)),
        "film_output": film_output,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    repo_default = Path(__file__).resolve().parent.parent
    ap.add_argument("--repo-root", type=Path, default=repo_default)
    ap.add_argument("--out-dir", type=Path, default=None, help="Output scene directory.")
    ap.add_argument(
        "--target",
        choices=("slanted_edge", "iso_noise", "siemens_star", "all"),
        default="all",
        help="Target to generate.",
    )
    ap.add_argument("--target-width", type=float, default=2.2)
    ap.add_argument("--target-height", type=float, default=1.6)

    ap.add_argument("--slanted-angle-deg", type=float, default=5.0)
    ap.add_argument("--slanted-edge-offset", type=float, default=0.15)

    ap.add_argument("--iso-rows", type=int, default=4)
    ap.add_argument("--iso-cols", type=int, default=6)
    ap.add_argument("--iso-min-reflectance", type=float, default=0.03)
    ap.add_argument("--iso-max-reflectance", type=float, default=0.9)

    ap.add_argument("--siemens-spokes", type=int, default=72)
    ap.add_argument("--siemens-radius-fraction", type=float, default=0.9)

    ap.add_argument("--light-scale", type=float, default=1.0)
    ap.add_argument("--cam-dist", type=float, default=3.2)
    ap.add_argument(
        "--camera",
        choices=("perspective", "pinhole", "thinlens", "realistic"),
        default="realistic",
    )
    ap.add_argument("--fov", type=float, default=32.0)
    ap.add_argument("--lensfile", type=str, default=DEFAULT_REALISTIC_LENSFILE)
    ap.add_argument("--aperture-diameter-mm", type=float, default=4.0)
    ap.add_argument("--focus-distance", type=float, default=None)
    ap.add_argument("--thinlens-lens-radius", type=float, default=0.03)
    ap.add_argument("--thinlens-focal-distance", type=float, default=None)

    ap.add_argument("--film", choices=("rgb", "spectral"), default="spectral")
    ap.add_argument("--xres", type=int, default=960)
    ap.add_argument("--yres", type=int, default=640)
    ap.add_argument("--pixelsamples", type=int, default=256)
    ap.add_argument("--spectral-nbuckets", type=int, default=32)
    ap.add_argument("--spectral-lambda-min", type=float, default=360.0)
    ap.add_argument("--spectral-lambda-max", type=float, default=830.0)
    args = ap.parse_args()

    repo = args.repo_root.resolve()
    out_dir = (args.out_dir or (repo / "scenes" / "generated" / "iq_targets")).resolve()
    (repo / "out").mkdir(parents=True, exist_ok=True)

    targets = ["slanted_edge", "iso_noise", "siemens_star"] if args.target == "all" else [args.target]
    manifest_items = [write_target_scene(args, repo, out_dir, t) for t in targets]
    manifest = {
        "generator": "tools/build_image_quality_targets.py",
        "out_dir": str(out_dir.relative_to(repo)),
        "targets": manifest_items,
    }
    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Wrote {len(manifest_items)} target scene(s) to {out_dir}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
