#!/usr/bin/env python3
"""Emissive HDR dynamic-range chart (pbrt scene + ROI manifest) for SNR / DR / CDP testing.

``n_levels`` log-spaced patches span ``span_db`` (default 120 dB = 1e6:1). Each patch is split
into a left half (luminance L, used for SNR and dynamic range) and a right half (L * k, with
k = (1 + C) / (1 - C)) so that every level also carries a fixed Michelson contrast ``C`` for the
IEEE P2020 contrast-detection-probability curve. Patches are diffuse area lights on a
zero-reflectance background with a pinhole camera, so there is no inter-patch light transport and
pbrt sees each patch's radiance noise-free. ROIs (raster pixels) go to ``chart.json`` for
``tools/run_hdr_dr_test.py``.

    venv/bin/python tools/build_hdr_dr_chart.py --out-dir scenes/iq_lab/hdr_dr_chart
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent


def chart_levels(n_levels: int, span_db: float) -> np.ndarray:
    """Relative luminance of the left half of each patch, brightest = 1."""
    return 10.0 ** (-np.linspace(0.0, span_db, n_levels)[::-1] / 20.0)


def contrast_ratio(michelson: float) -> float:
    if not 0.0 < michelson < 1.0:
        raise ValueError("Michelson contrast must be in (0, 1)")
    return (1.0 + michelson) / (1.0 - michelson)


def layout(args: argparse.Namespace) -> dict:
    """World-space patch rectangles and their raster ROIs for a pinhole at (0, 0, cam_dist) looking at -z."""
    n, cols = int(args.n_levels), int(args.cols)
    rows = math.ceil(n / cols)
    half_h = float(args.cam_dist) * math.tan(math.radians(float(args.fov)) / 2.0)  # pbrt fov spans the short axis
    aspect = float(args.xres) / float(args.yres)
    if aspect < 1:
        raise ValueError("use xres >= yres")
    half_w = half_h * aspect
    pitch = min(2 * half_w * 0.94 / cols, 2 * half_h * 0.94 / rows)
    size = pitch * float(args.patch_fill)
    levels = chart_levels(n, float(args.span_db))
    k = contrast_ratio(float(args.contrast))
    shrink = float(args.roi_fraction)

    def to_raster(x: float, y: float) -> tuple[float, float]:
        # pbrt LookAt with up=+y and view along -z puts world +x on the raster *left* (camera x = -world x)
        return (0.5 - 0.5 * x / half_w) * float(args.xres), (0.5 - 0.5 * y / half_h) * float(args.yres)

    patches = []
    for i, lv in enumerate(levels):
        r, c = divmod(i, cols)
        cx = (c - (cols - 1) / 2.0) * pitch
        cy = ((rows - 1) / 2.0 - r) * pitch
        halves = {}
        for name, x0, x1, val in (
            ("low", cx - size / 2, cx, lv),
            ("high", cx, cx + size / 2, lv * k),
        ):
            y0, y1 = cy - size / 2, cy + size / 2
            mx, my = (x1 - x0) * (1 - shrink) / 2, (y1 - y0) * (1 - shrink) / 2
            (ra, rb), (rc, rd) = to_raster(x0 + mx, y1 - my), to_raster(x1 - mx, y0 + my)
            roi = [int(math.ceil(min(ra, rc))), int(math.ceil(rb)), int(math.floor(max(ra, rc))), int(math.floor(rd))]
            halves[name] = {"world": [x0, y0, x1, y1], "relative_luminance": float(val), "roi_xyxy": roi}
        patches.append({"index": i, "level_db": float(20 * np.log10(lv)), **halves})
    return {
        "n_levels": n,
        "span_db": float(args.span_db),
        "michelson_contrast": float(args.contrast),
        "contrast_ratio": k,
        "peak_radiance": float(args.peak_radiance),
        "xres": int(args.xres),
        "yres": int(args.yres),
        "patches": patches,
    }


def scene_lines(args: argparse.Namespace, chart: dict, film_output: str) -> list[str]:
    film = (
        [
            'Film "spectral"',
            f'    "string filename" ["{film_output}"]',
            f'    "integer xresolution" [{int(args.xres)}]',
            f'    "integer yresolution" [{int(args.yres)}]',
            '    "bool savefp16" false',
            f'    "integer nbuckets" [{int(args.spectral_nbuckets)}]',
            '    "float lambdamin" [360]',
            '    "float lambdamax" [830]',
        ]
        if args.film == "spectral"
        else [
            'Film "rgb"',
            f'    "string filename" ["{film_output}"]',
            f'    "integer xresolution" [{int(args.xres)}]',
            f'    "integer yresolution" [{int(args.yres)}]',
            '    "bool savefp16" false',
        ]
    )
    out = [
        "# Generated by tools/build_hdr_dr_chart.py",
        'Option "seed" 0',
        'ColorSpace "srgb"',
        f'Sampler "zsobol" "integer pixelsamples" [{int(args.pixelsamples)}]',
        'Integrator "path" "integer maxdepth" [1]',
        'PixelFilter "box" "float xradius" [0.5] "float yradius" [0.5]',
        *film,
        "",
        f"LookAt 0 0 {float(args.cam_dist):.6g}  0 0 0  0 1 0",
        f'Camera "perspective" "float fov" [{float(args.fov):.6g}]',
        "",
        "WorldBegin",
        "",
        "AttributeBegin",
        '    Material "diffuse" "rgb reflectance" [0 0 0]',
        '    Shape "bilinearmesh" "point3 P" [ -50 -50 -0.01  50 -50 -0.01  -50 50 -0.01  50 50 -0.01 ]',
        "AttributeEnd",
        "",
    ]
    peak = float(args.peak_radiance)
    for p in chart["patches"]:
        for half in ("low", "high"):
            x0, y0, x1, y1 = p[half]["world"]
            L = peak * p[half]["relative_luminance"] / chart["contrast_ratio"]
            out += [
                "AttributeBegin",
                f'    AreaLightSource "diffuse" "rgb L" [{L:.6g} {L:.6g} {L:.6g}]',
                '    Material "diffuse" "rgb reflectance" [0 0 0]',
                f'    Shape "bilinearmesh" "point3 P" [ {x0:.6g} {y0:.6g} 0  {x1:.6g} {y0:.6g} 0  {x0:.6g} {y1:.6g} 0  {x1:.6g} {y1:.6g} 0 ]',
                "AttributeEnd",
            ]
    return out


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", type=Path, default=REPO / "scenes" / "iq_lab" / "hdr_dr_chart")
    ap.add_argument("--n-levels", type=int, default=21)
    ap.add_argument("--cols", type=int, default=7)
    ap.add_argument("--span-db", type=float, default=120.0)
    ap.add_argument("--contrast", type=float, default=0.2, help="Michelson contrast between patch halves")
    ap.add_argument("--peak-radiance", type=float, default=1000.0, help="pbrt rgb L of the brightest (high) half")
    ap.add_argument("--patch-fill", type=float, default=0.8)
    ap.add_argument("--roi-fraction", type=float, default=0.6, help="ROI size relative to each half-patch")
    ap.add_argument("--cam-dist", type=float, default=3.0)
    ap.add_argument("--fov", type=float, default=30.0)
    ap.add_argument("--xres", type=int, default=960)
    ap.add_argument("--yres", type=int, default=480)
    ap.add_argument("--pixelsamples", type=int, default=16)
    ap.add_argument("--film", choices=("spectral", "rgb"), default="spectral")
    ap.add_argument("--spectral-nbuckets", type=int, default=32)
    return ap


def write_chart(args: argparse.Namespace) -> dict:
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    chart = layout(args)
    film_output = f"hdr_dr_chart_{args.film}.exr"
    (out_dir / "hdr_dr_chart.pbrt").write_text("\n".join(scene_lines(args, chart, film_output)) + "\n")
    chart["scene"] = "hdr_dr_chart.pbrt"
    chart["film_output"] = film_output
    (out_dir / "chart.json").write_text(json.dumps(chart, indent=2))
    return chart


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    chart = write_chart(args)
    print(f"wrote {args.out_dir}/hdr_dr_chart.pbrt ({chart['n_levels']} levels, {chart['span_db']:g} dB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
