#!/usr/bin/env python3
"""Spectral skin-tone chart (pbrt) rendered under several illuminants, plus reference CIELAB.

12 patches in a 4 x 3 grid: 8 synthetic melanin-series skin tones (ITA ~ +60 ... -45, see
``iqlab/skin.py``), the measured ColorChecker light/dark skin, a 90 % white and an 18 % grey. One scene
per illuminant (``--illuminants``, any ``spectra/illuminant/interpolated`` id). ``chart.json`` holds
patch ROIs (raster px) and reference L*a*b* per illuminant (white = perfect diffuser, same illuminant).
Score renders with ``tools/run_skin_tone_test.py``.

    venv/bin/python tools/build_skin_tone_chart.py --out-dir scenes/iq_lab/skin_tones
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import build_image_quality_targets as iq
import numpy as np
from colour_science import load_illuminant
from iqlab import skin

REPO = Path(__file__).resolve().parent.parent
COLS, ROWS = 4, 3


def patches(wl: np.ndarray) -> list[dict]:
    p = skin.skin_tone_set(REPO, wl)
    p.append({"name": "white90", "source": "flat", "tau": None, "reflectance": np.full_like(wl, 0.9)})
    p.append({"name": "grey18", "source": "flat", "tau": None, "reflectance": np.full_like(wl, 0.18)})
    return p


def _spd(path: Path, wl: np.ndarray, val: np.ndarray) -> None:
    path.write_text("".join(f"{a:.1f} {b:.6g}\n" for a, b in zip(wl, val)))


def layout(args: argparse.Namespace) -> list[dict]:
    pw, g = float(args.patch_size), float(args.gap)
    bw, bh = COLS * pw + (COLS - 1) * g, ROWS * pw + (ROWS - 1) * g
    hh = float(args.cam_dist) * math.tan(math.radians(float(args.fov)) / 2.0)
    hw = hh * args.xres / args.yres
    out = []
    for k in range(COLS * ROWS):
        r, c = divmod(k, COLS)
        x0 = -bw / 2 + c * (pw + g)
        y1 = bh / 2 - r * (pw + g)
        # pbrt LookAt: world +x -> raster left
        px0 = (hw - (x0 + pw)) / (2 * hw) * args.xres
        px1 = (hw - x0) / (2 * hw) * args.xres
        py0 = (hh - y1) / (2 * hh) * args.yres
        py1 = (hh - (y1 - pw)) / (2 * hh) * args.yres
        m = float(args.roi_margin)
        dx, dy = (px1 - px0) * m, (py1 - py0) * m
        out.append(
            {
                "world": [x0, y1 - pw, x0 + pw, y1],
                "roi_xyxy": [int(math.ceil(px0 + dx)), int(math.ceil(py0 + dy)), int(px1 - dx), int(py1 - dy)],
            }
        )
    return out


def scene_lines(args, ill_name: str, geo: list[dict], film: str) -> list[str]:
    lines = [
        f"# Generated by tools/build_skin_tone_chart.py ({ill_name})",
        'Option "seed" 0',
        'ColorSpace "srgb"',
        f'Sampler "zsobol" "integer pixelsamples" [{int(args.pixelsamples)}]',
        'Integrator "path" "integer maxdepth" [1]',
        'PixelFilter "gaussian"',
        *iq._film_block(args, film),
        f"LookAt 0 0 {float(args.cam_dist):.6g}  0 0 0  0 1 0",
        *iq._camera_block(args, Path(args.out_dir), REPO),
        "WorldBegin",
        f'LightSource "distant" "spectrum L" "spd/illuminant_{ill_name}.spd" "point3 from" [0 0 1] "point3 to" [0 0 0] '
        f'"float illuminance" [{float(args.illuminance):.6g}]',
    ]
    for k, gg in enumerate(geo):
        x0, y0, x1, y1 = gg["world"]
        lines += [
            "AttributeBegin",
            f'    Material "diffuse" "spectrum reflectance" "spd/patch_{k:02d}.spd"',
            f'    Shape "bilinearmesh" "point3 P" [ {x0:.6g} {y0:.6g} 0  {x1:.6g} {y0:.6g} 0  {x0:.6g} {y1:.6g} 0  {x1:.6g} {y1:.6g} 0 ]',
            "AttributeEnd",
        ]
    return lines


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", type=Path, default=REPO / "scenes" / "iq_lab" / "skin_tones")
    ap.add_argument("--illuminants", nargs="+", default=["D65", "A", "F11", "LED_B4"])
    ap.add_argument("--illuminance", type=float, default=1000.0, help="lux at the chart")
    ap.add_argument("--patch-size", type=float, default=0.2)
    ap.add_argument("--gap", type=float, default=0.03)
    ap.add_argument("--roi-margin", type=float, default=0.2)
    ap.add_argument("--camera", choices=("perspective", "thinlens", "realistic"), default="perspective")
    ap.add_argument("--lensfile", default=iq.DEFAULT_REALISTIC_LENSFILE)
    ap.add_argument("--aperture-diameter-mm", type=float, default=4.0)
    ap.add_argument("--focus-distance", type=float, default=None)
    ap.add_argument("--thinlens-lens-radius", type=float, default=0.0)
    ap.add_argument("--thinlens-focal-distance", type=float, default=None)
    ap.add_argument("--fov", type=float, default=40.0)
    ap.add_argument("--cam-dist", type=float, default=1.5)
    ap.add_argument("--film", choices=("spectral", "rgb"), default="spectral")
    ap.add_argument("--xres", type=int, default=960)
    ap.add_argument("--yres", type=int, default=640)
    ap.add_argument("--pixelsamples", type=int, default=64)
    ap.add_argument("--spectral-nbuckets", type=int, default=32)
    ap.add_argument("--spectral-lambda-min", type=float, default=360.0)
    ap.add_argument("--spectral-lambda-max", type=float, default=830.0)
    return ap


def write_chart(args: argparse.Namespace) -> dict:
    out = Path(args.out_dir)
    (out / "spd").mkdir(parents=True, exist_ok=True)
    wl = np.arange(360.0, 831.0, 5.0)
    pats, geo = patches(wl), layout(args)
    for k, p in enumerate(pats):
        _spd(out / "spd" / f"patch_{k:02d}.spd", wl, p["reflectance"])
    refl = np.stack([p["reflectance"] for p in pats])
    chart = {
        "white_index": len(pats) - 2,
        "grey_index": len(pats) - 1,
        "xres": args.xres,
        "yres": args.yres,
        "patches": [],
        "scenes": {},
    }
    labs = {}
    for ill in args.illuminants:
        _, spd = load_illuminant(REPO, ill, wl)
        _spd(out / "spd" / f"illuminant_{ill}.spd", wl, spd)
        labs[ill] = skin.reflectance_lab(wl, refl, spd)
        film = f"skin_tones_{ill}_{args.film}.exr"
        (out / f"skin_tones_{ill}.pbrt").write_text("\n".join(scene_lines(args, ill, geo, film)) + "\n")
        chart["scenes"][ill] = {"scene": f"skin_tones_{ill}.pbrt", "film_output": film}
    for k, (p, gg) in enumerate(zip(pats, geo)):
        chart["patches"].append(
            {
                "name": p["name"],
                "source": p["source"],
                "tau": p["tau"],
                **gg,
                "reference_lab": {ill: labs[ill][k].tolist() for ill in labs},
            }
        )
    (out / "chart.json").write_text(json.dumps(chart, indent=2))
    return chart


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    write_chart(args)
    print(f"wrote skin-tone chart for {', '.join(args.illuminants)} to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
