#!/usr/bin/env python3
"""Lens-flare / veiling-glare test scenes for the IQ lab.

* ``veiling_glare``: ISO 18844-style black-hole target -- a uniform emissive field filling the view with
  zero-reflectance "holes" at the centre, 4 diagonal and 4 edge field positions. Score with
  ``tools/run_flare_test.py --exr`` (hole signal / surround = veiling glare %).
* ``point_sweep``: one scene per field angle with a single small bright disc emitter on a black
  background, stepped from the axis to ``--max-field-deg`` -- render with the realistic lens and add
  traced ghosts with ``tools/lens_ghosts.py``, then score ghost peak / stray-light fraction vs angle.

pbrt's RealisticCamera has no inter-reflections, so ghosts come from ``lens_ghosts.py`` (Hullin et al.
2011 two-reflection paths); this builder only makes the scenes.

    venv/bin/python tools/build_flare_test_scene.py --out-dir scenes/iq_lab/flare --camera realistic
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import build_image_quality_targets as iq

REPO = Path(__file__).resolve().parent.parent
HOLE_POSITIONS = (
    [(0.0, 0.0)]
    + [(sx * 0.7, sy * 0.7) for sx in (-1, 1) for sy in (-1, 1)]
    + [
        (0.75, 0.0),
        (-0.75, 0.0),
        (0.0, 0.75),
        (0.0, -0.75),
    ]
)


def _header(args: argparse.Namespace, out_dir: Path, film_output: str, label: str) -> list[str]:
    return [
        f"# Generated by tools/build_flare_test_scene.py ({label})",
        'Option "seed" 0',
        'ColorSpace "srgb"',
        f'Sampler "zsobol" "integer pixelsamples" [{int(args.pixelsamples)}]',
        'Integrator "path" "integer maxdepth" [2]',
        'PixelFilter "gaussian"',
        *iq._film_block(args, film_output),
        "",
        f"LookAt 0 0 {float(args.cam_dist):.6g}  0 0 0  0 1 0",
        *iq._camera_block(args, out_dir, REPO),
        "",
        "WorldBegin",
        "",
    ]


def _quad(x0: float, y0: float, x1: float, y1: float, z: float) -> str:
    return f'    Shape "bilinearmesh" "point3 P" [ {x0:.6g} {y0:.6g} {z}  {x1:.6g} {y0:.6g} {z}  {x0:.6g} {y1:.6g} {z}  {x1:.6g} {y1:.6g} {z} ]'


def half_extent(args: argparse.Namespace) -> tuple[float, float]:
    """Half width/height (m) of the view at the target plane, from the pinhole fov (short axis)."""
    hh = float(args.cam_dist) * math.tan(math.radians(float(args.fov)) / 2.0)
    return hh * float(args.xres) / float(args.yres), hh


def veiling_glare_lines(args: argparse.Namespace) -> list[str]:
    hw, hh = half_extent(args)
    s = float(args.field_scale)
    L = float(args.field_radiance)
    lines = [
        "AttributeBegin",
        f'    AreaLightSource "diffuse" "rgb L" [{L:.6g} {L:.6g} {L:.6g}]',
        '    Material "diffuse" "rgb reflectance" [0 0 0]',
        _quad(-hw * s, -hh * s, hw * s, hh * s, 0),
        "AttributeEnd",
    ]
    r = float(args.hole_size) * hh / 2.0
    for fx, fy in HOLE_POSITIONS:
        cx, cy = fx * hw, fy * hh
        lines += [
            "AttributeBegin",
            '    Material "diffuse" "rgb reflectance" [0 0 0]',
            _quad(cx - r, cy - r, cx + r, cy + r, 0.001),
            "AttributeEnd",
        ]
    return lines


def point_source_lines(args: argparse.Namespace, field_deg: float) -> list[str]:
    x = -float(args.cam_dist) * math.tan(math.radians(field_deg))  # world -x -> raster right
    L = float(args.source_radiance)
    return [
        "AttributeBegin",
        '    Material "diffuse" "rgb reflectance" [0 0 0]',
        _quad(-50, -50, 50, 50, -0.01),
        "AttributeEnd",
        "AttributeBegin",
        f"    Translate {x:.6g} 0 0",
        f'    AreaLightSource "diffuse" "rgb L" [{L:.6g} {L:.6g} {L:.6g}]',
        f'    Shape "disk" "float radius" [{float(args.source_radius):.6g}]',
        "AttributeEnd",
    ]


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", type=Path, default=REPO / "scenes" / "iq_lab" / "flare")
    ap.add_argument(
        "--targets", nargs="+", choices=("veiling_glare", "point_sweep"), default=["veiling_glare", "point_sweep"]
    )
    ap.add_argument("--camera", choices=("realistic", "perspective", "thinlens"), default="realistic")
    ap.add_argument("--lensfile", default=iq.DEFAULT_REALISTIC_LENSFILE)
    ap.add_argument("--aperture-diameter-mm", type=float, default=4.0)
    ap.add_argument("--focus-distance", type=float, default=None)
    ap.add_argument("--thinlens-lens-radius", type=float, default=0.0)
    ap.add_argument("--thinlens-focal-distance", type=float, default=None)
    ap.add_argument("--fov", type=float, default=60.0, help="pinhole fov; also sizes the targets")
    ap.add_argument("--cam-dist", type=float, default=2.0)
    ap.add_argument("--field-radiance", type=float, default=10.0)
    ap.add_argument("--field-scale", type=float, default=1.6, help="emissive field size relative to the view")
    ap.add_argument("--hole-size", type=float, default=0.12, help="hole side / view height")
    ap.add_argument("--source-radiance", type=float, default=1.0e5)
    ap.add_argument("--source-radius", type=float, default=0.01)
    ap.add_argument("--max-field-deg", type=float, default=30.0)
    ap.add_argument("--field-steps", type=int, default=7)
    ap.add_argument("--film", choices=("spectral", "rgb"), default="spectral")
    ap.add_argument("--xres", type=int, default=960)
    ap.add_argument("--yres", type=int, default=640)
    ap.add_argument("--pixelsamples", type=int, default=256)
    ap.add_argument("--spectral-nbuckets", type=int, default=32)
    ap.add_argument("--spectral-lambda-min", type=float, default=360.0)
    ap.add_argument("--spectral-lambda-max", type=float, default=830.0)
    return ap


def write_scenes(args: argparse.Namespace) -> dict:
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    manifest: dict = {"camera": args.camera, "lensfile": args.lensfile, "fov": args.fov, "scenes": []}
    if "veiling_glare" in args.targets:
        film = f"veiling_glare_{args.film}.exr"
        (out / "veiling_glare.pbrt").write_text(
            "\n".join(_header(args, out, film, "veiling_glare") + veiling_glare_lines(args)) + "\n"
        )
        manifest["scenes"].append(
            {
                "target": "veiling_glare",
                "scene": "veiling_glare.pbrt",
                "film_output": film,
                "n_holes": len(HOLE_POSITIONS),
            }
        )
    if "point_sweep" in args.targets:
        n = int(args.field_steps)
        for k in range(n):
            ang = float(args.max_field_deg) * k / max(n - 1, 1)
            name = f"point_{ang:05.1f}deg".replace(".", "p")
            film = f"{name}_{args.film}.exr"
            (out / f"{name}.pbrt").write_text(
                "\n".join(_header(args, out, film, name) + point_source_lines(args, ang)) + "\n"
            )
            manifest["scenes"].append(
                {"target": "point_sweep", "field_deg": ang, "scene": f"{name}.pbrt", "film_output": film}
            )
    (out / "flare_manifest.json").write_text(json.dumps(manifest, indent=2))
    return manifest


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    m = write_scenes(args)
    print(f"wrote {len(m['scenes'])} scenes to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
