#!/usr/bin/env python3
"""Generate a high-contrast PBRT scene for testing lens/sensor stray light.

Scene design goals:
- Large dark field to reveal veiling glare (black lift).
- Very bright emitters to generate halo/flare spread.
- One emitter near image center and one near the field edge to stress off-axis behavior.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

LEGACY_REALISTIC_LENSFILE = "scenes/lenses/wide_22mm.dat"
DEFAULT_REALISTIC_LENSFILE = "config/lenses/wide_22mm.dat"


def resolve_lensfile(repo: Path, lensfile_rel: str) -> Path:
    lens_path = (repo / lensfile_rel).resolve()
    if lens_path.is_file():
        return lens_path
    if lensfile_rel == LEGACY_REALISTIC_LENSFILE:
        migrated = (repo / DEFAULT_REALISTIC_LENSFILE).resolve()
        if migrated.is_file():
            return migrated
    return lens_path


def _camera_block(args: argparse.Namespace, scene_dir: Path, repo: Path) -> list[str]:
    focus_d = float(args.focus_distance) if args.focus_distance is not None else float(args.cam_dist)
    if args.camera == "perspective":
        return [f'Camera "perspective" "float fov" [{float(args.fov):.6g}]']

    lens_repo = resolve_lensfile(repo, args.lensfile)
    if not lens_repo.is_file():
        raise FileNotFoundError(f"realistic camera: lens file not found: {lens_repo}")
    lens_for_scene = os.path.relpath(str(lens_repo), str(scene_dir.resolve()))
    return [
        'Camera "realistic"',
        f'    "string lensfile" ["{lens_for_scene}"]',
        f'    "float aperturediameter" [{float(args.aperture_diameter_mm):.6g}]',
        f'    "float focusdistance" [{focus_d:.6g}]',
    ]


def _film_block(args: argparse.Namespace) -> list[str]:
    film = str(args.film).lower()
    if film == "rgb":
        return [
            'Film "rgb"',
            f'    "string filename" ["{args.film_output}"]',
            f'    "integer xresolution" [{int(args.xres)}]',
            f'    "integer yresolution" [{int(args.yres)}]',
            '    "bool savefp16" false',
            '    "float iso" [100]',
        ]
    return [
        'Film "spectral"',
        f'    "string filename" ["{args.film_output}"]',
        f'    "integer xresolution" [{int(args.xres)}]',
        f'    "integer yresolution" [{int(args.yres)}]',
        '    "bool savefp16" false',
        f'    "integer nbuckets" [{int(args.spectral_nbuckets)}]',
        f'    "float lambdamin" [{float(args.spectral_lambda_min):.6g}]',
        f'    "float lambdamax" [{float(args.spectral_lambda_max):.6g}]',
    ]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    repo_default = Path(__file__).resolve().parent.parent
    ap.add_argument("--repo-root", type=Path, default=repo_default)
    ap.add_argument(
        "--out-scene",
        type=Path,
        default=None,
        help="Output PBRT scene path (default: scenes/generated/straylight_test.pbrt)",
    )
    ap.add_argument(
        "--film",
        choices=("rgb", "spectral"),
        default="spectral",
        help="PBRT film type.",
    )
    ap.add_argument(
        "--film-output",
        type=str,
        default="out/straylight_test_spectral.exr",
        help="Film output path relative to repo root.",
    )
    ap.add_argument("--xres", type=int, default=960)
    ap.add_argument("--yres", type=int, default=640)
    ap.add_argument("--pixelsamples", type=int, default=1024)
    ap.add_argument("--spectral-nbuckets", type=int, default=32)
    ap.add_argument("--spectral-lambda-min", type=float, default=360.0)
    ap.add_argument("--spectral-lambda-max", type=float, default=830.0)
    ap.add_argument("--cam-dist", type=float, default=3.0)
    ap.add_argument(
        "--camera",
        choices=("perspective", "realistic"),
        default="realistic",
    )
    ap.add_argument("--fov", type=float, default=35.0)
    ap.add_argument("--lensfile", type=str, default=DEFAULT_REALISTIC_LENSFILE)
    ap.add_argument("--aperture-diameter-mm", type=float, default=4.0)
    ap.add_argument("--focus-distance", type=float, default=None)
    ap.add_argument("--bg-reflectance", type=float, default=0.02, help="Dark field reflectance (0..1)")
    ap.add_argument("--bright-radiance", type=float, default=250.0, help="Radiance of bright area emitters")
    ap.add_argument("--fill-radiance", type=float, default=0.35, help="Very dim scene fill area light")
    args = ap.parse_args()

    repo = args.repo_root.resolve()
    out_scene = (args.out_scene or (repo / "scenes" / "generated" / "straylight_test.pbrt")).resolve()
    out_scene.parent.mkdir(parents=True, exist_ok=True)
    (repo / "out").mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Generated by tools/build_straylight_test_scene.py — do not hand-edit.",
        'Option "disablepixeljitter" false',
        'Option "seed" 0',
        "",
        'ColorSpace "srgb"',
        "",
        f'Sampler "zsobol" "integer pixelsamples" [{int(args.pixelsamples)}]',
        'Integrator "path" "integer maxdepth" [8]',
        'PixelFilter "gaussian"',
        "",
        *_film_block(args),
        "",
        "LookAt",
        f"0 0 {float(args.cam_dist):.6f}",
        "    0 0 0",
        "    0 1 0",
        *_camera_block(args, out_scene.parent, repo),
        "",
        "WorldBegin",
        "",
        "# Dark wall at z=0 to expose veiling glare/contrast loss.",
        "AttributeBegin",
        f'    Material "diffuse" "rgb reflectance" [{float(args.bg_reflectance):.6g} {float(args.bg_reflectance):.6g} {float(args.bg_reflectance):.6g}]',
        '    Shape "bilinearmesh"',
        '        "point3 P" [ -1.8 -1.2 0.0   1.8 -1.2 0.0   -1.8 1.2 0.0   1.8 1.2 0.0 ]',
        '        "point2 uv" [ 0 0   1 0   0 1   1 1 ]',
        "AttributeEnd",
        "",
        "# Bright center emitter.",
        "AttributeBegin",
        f'    AreaLightSource "diffuse" "rgb L" [{float(args.bright_radiance):.6g} {float(args.bright_radiance):.6g} {float(args.bright_radiance):.6g}]',
        '    Material "diffuse" "rgb reflectance" [1 1 1]',
        '    Shape "disk" "float radius" [0.08]',
        "AttributeEnd",
        "",
        "# Bright off-axis emitter near frame edge (stress stray-light asymmetry).",
        "AttributeBegin",
        "    Translate 1.05 0.58 0.0",
        f'    AreaLightSource "diffuse" "rgb L" [{float(args.bright_radiance):.6g} {float(args.bright_radiance):.6g} {float(args.bright_radiance):.6g}]',
        '    Material "diffuse" "rgb reflectance" [1 1 1]',
        '    Shape "disk" "float radius" [0.065]',
        "AttributeEnd",
        "",
        "# Very dim broad fill to avoid absolute-black clipping in reference renders.",
        "AttributeBegin",
        "    Translate -1.0 -0.65 0.0",
        f'    AreaLightSource "diffuse" "rgb L" [{float(args.fill_radiance):.6g} {float(args.fill_radiance):.6g} {float(args.fill_radiance):.6g}]',
        '    Material "diffuse" "rgb reflectance" [1 1 1]',
        '    Shape "disk" "float radius" [0.22]',
        "AttributeEnd",
        "",
    ]

    out_scene.write_text("\n".join(lines) + "\n")
    print(f"Wrote scene: {out_scene}")
    print(f"Film output: {args.film_output}")


if __name__ == "__main__":
    main()
