#!/usr/bin/env python3
"""Validate a camera recipe against real captures from a physical camera.

Inputs (see docs/REAL_CAMERA_VALIDATION.md for the capture protocol and the
``capture.yaml`` layout):

* dark and flat-field raw stacks  -> EMVA 1288 photon-transfer parameters
  (K, read noise, DSNU, PRNU, dark current, saturation capacity);
* a ColorChecker raw              -> per-patch electrons and colour error;
* a slanted-edge raw              -> ISO 12233 SFR / MTF.

For each measurement the matching simulation is run with the recipe (same
signal levels, exposure times, frame counts and ROI sizes), and measured,
recipe and simulated values are reported side by side. Comparing measured
against *simulated* (not just against the recipe numbers) removes estimator
bias shared by both -- finite frame counts, quantisation, the EMVA definition
of saturation at the variance peak.

``synthesize`` writes a complete capture set generated by the simulator itself
(tools/apply_emva_noise.py), so the harness can be round-trip tested without a
camera. Real captures are needed for an actual validation.

References: EMVA Standard 1288, Release 4.0 (2021), *Standard for
Characterization of Image Sensors and Cameras* (photon transfer, sections on
temporal noise, saturation, dark current, DSNU1288/PRNU1288); ISO 12233:2017 /
2023 (slanted-edge SFR); CIE 15:2018 / CIEDE2000 (colour difference).

Examples::

    venv/bin/python tools/validate_against_capture.py synthesize \\
        --recipe config/camera_recipes/default.yaml --out-dir out/capture_synth
    venv/bin/python tools/validate_against_capture.py validate \\
        --capture out/capture_synth/capture.yaml --out-dir out/capture_synth/report --plot
"""

from __future__ import annotations

import argparse
import copy
import glob
import json
import math
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parent
sys.path.insert(0, str(TOOLS))

import colour_science as cs  # noqa: E402
import emva_theory as et  # noqa: E402
import sfr_analysis as sfr  # noqa: E402
from camera_model import effective_f_number, load_camera_model  # noqa: E402

SCHEMA_VERSION = 1
#: EMVA 1288 fits K over 0..70 % of the saturation mean.
K_FIT_MAX_FRACTION_OF_SAT = 0.7
#: Quantisation noise of an ideal ADC, DN^2 (EMVA 1288: sigma_q^2 = 1/12).
QUANTISATION_VAR_DN2 = 1.0 / 12.0
WHITE_PATCH = 18  # ColorChecker patch 19 (white 9.5), zero-based
SPECTRAL_GRID_NM = np.arange(380.0, 731.0, 5.0)


# =====================================================================
# Raw I/O and CFA handling
# =====================================================================
def read_raw(path: Path, fmt: dict) -> tuple[np.ndarray, dict]:
    """Read one raw frame as float DN, plus any metadata found in the file.

    ``raw16``: headerless little-endian uint16 (what apply_emva_noise writes),
    shape from ``fmt["height"]``/``fmt["width"]``. ``npy``: a 2-D array.
    ``dng`` (or any LibRaw format): via the optional ``rawpy`` package; black
    level, white level and CFA pattern are taken from the file.
    """
    path = Path(path)
    kind = str(fmt.get("format") or path.suffix.lstrip(".")).lower()
    meta: dict = {}
    if kind == "raw16":
        h, w = int(fmt["height"]), int(fmt["width"])
        data = np.fromfile(path, dtype="<u2")
        if data.size != h * w:
            raise ValueError(f"{path}: {data.size} samples, expected {h}x{w}={h * w}")
        return data.reshape(h, w).astype(np.float64), meta
    if kind == "npy":
        return np.asarray(np.load(path), dtype=np.float64), meta
    try:
        import rawpy  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise ImportError(f"reading {path} ({kind}) needs the optional 'rawpy' package: pip install rawpy") from exc
    with rawpy.imread(str(path)) as raw:  # pragma: no cover - needs real DNGs
        img = raw.raw_image_visible.astype(np.float64)
        meta["black_level_DN"] = float(np.mean(raw.black_level_per_channel))
        meta["white_level_DN"] = float(raw.white_level)
        desc = raw.color_desc.decode()
        pat = raw.raw_pattern[:2, :2].ravel()
        meta["cfa_pattern"] = "".join(desc[i] for i in pat).replace("G", "G")
    return img, meta


def cfa_offsets(pattern: str | None) -> dict[str, list[tuple[int, int]]]:
    """(row, col) offsets of each colour inside the 2x2 CFA tile."""
    if not pattern:
        return {"R": [(0, 0)], "G": [(0, 0)], "B": [(0, 0)]}
    p = pattern.upper()
    if len(p) != 4 or sorted(p) != ["B", "G", "G", "R"]:
        raise ValueError(f"unsupported CFA pattern {pattern!r}; expected a Bayer RGGB/GRBG/GBRG/BGGR")
    out: dict[str, list[tuple[int, int]]] = {"R": [], "G": [], "B": []}
    for i, ch in enumerate(p):
        out[ch].append((i // 2, i % 2))
    return out


def cfa_plane(img: np.ndarray, pattern: str | None, colour: str = "G", index: int = 0) -> np.ndarray:
    """One colour sub-plane (half resolution for Bayer; the image itself for mono)."""
    if not pattern:
        return img
    r, c = cfa_offsets(pattern)[colour.upper()][index]
    return img[r::2, c::2]


def crop(img: np.ndarray, roi: list | None) -> np.ndarray:
    """Crop ``[x0, y0, x1, y1]``; the origin is rounded down to even to keep CFA phase."""
    if roi is None:
        return img
    x0, y0, x1, y1 = (int(v) for v in roi)
    return img[y0 - (y0 % 2) : y1, x0 - (x0 % 2) : x1]


def colour_mean(img: np.ndarray, pattern: str | None, colour: str) -> float:
    planes = [cfa_plane(img, pattern, colour, i) for i in range(len(cfa_offsets(pattern)[colour.upper()]))]
    return float(np.mean([p.mean() for p in planes]))


# =====================================================================
# Capture manifest
# =====================================================================
@dataclass
class Capture:
    root: Path
    cfg: dict

    @property
    def raw(self) -> dict:
        return self.cfg.get("raw", {}) or {}

    @property
    def pattern(self) -> str | None:
        return self.raw.get("cfa_pattern")

    def fmt(self, section: dict | None = None) -> dict:
        f = dict(self.raw)
        for k in ("format", "width", "height"):
            if section and k in section:
                f[k] = section[k]
        return f

    def files(self, spec: str | list) -> list[Path]:
        items = spec if isinstance(spec, list) else [spec]
        out: list[Path] = []
        for it in items:
            matches = sorted(glob.glob(str(self.root / it)))
            if not matches:
                raise FileNotFoundError(f"no files match {self.root / it}")
            out.extend(Path(m) for m in matches)
        return out

    def stack(self, entry: dict, roi: list | None, colour: str) -> np.ndarray:
        frames = [read_raw(p, self.fmt(entry))[0] for p in self.files(entry["frames"])]
        if len(frames) < 2:
            raise ValueError(f"EMVA stacks need >= 2 frames, got {len(frames)} for {entry['frames']}")
        return np.stack([cfa_plane(crop(f, roi), self.pattern, colour) for f in frames])


def load_capture(path: Path) -> Capture:
    path = Path(path).resolve()
    cfg = yaml.safe_load(path.read_text()) or {}
    if int(cfg.get("schema_version", SCHEMA_VERSION)) != SCHEMA_VERSION:
        raise ValueError(f"{path}: unsupported capture schema_version {cfg.get('schema_version')}")
    return Capture(root=path.parent, cfg=cfg)


def resolve_recipe(capture: Capture, override: Path | None) -> Path:
    ref = override or capture.cfg.get("camera_recipe")
    if ref is None:
        raise ValueError("no camera recipe: set camera_recipe in capture.yaml or pass --recipe")
    p = Path(ref)
    for cand in (p, REPO / p, capture.root / p):
        if cand.is_file():
            return cand.resolve()
    raise FileNotFoundError(f"camera recipe not found: {ref}")


# =====================================================================
# Recipe parameters
# =====================================================================
def recipe_emva(model: dict, temperature_c: float | None = None) -> dict:
    """The recipe's EMVA parameters, as apply_emva_noise would use them."""
    emva = model["noise"]["emva"]
    adc = model["noise"]["adc"]
    gain = float(emva.get("iso_gain_factor", 1.0))
    # Same ISO scaling as apply_emva_noise.iso_scaled_conversion.
    k = float(emva["overall_system_gain_K_e_per_DN"]) / gain
    fw = float(adc["full_well_e"]) / gain
    t_ref = float(emva.get("dark_current_reference_temp_c", 20.0))
    t = float(emva.get("temperature_c", t_ref)) if temperature_c is None else float(temperature_c)
    doubling = max(float(emva.get("dark_current_doubling_per_c", 6.0)), 1e-6)
    return {
        "K_e_per_DN": k,
        "read_noise_e": math.hypot(float(emva.get("sigma_d_e", 0.0)), float(emva.get("sigma_amp_e", 0.0)) * gain),
        "dsnu_e": float(emva.get("dsnu_std_e", 0.0)),
        "prnu_fraction": float(emva.get("prnu_std_fraction", 0.0)),
        "dark_current_e_per_s": float(emva.get("dark_current_e_per_s", 0.0)) * 2.0 ** ((t - t_ref) / doubling),
        "full_well_e": fw,
        "black_level_DN": float(emva.get("black_level_DN", 0.0)),
        "bit_depth": int(adc.get("bit_depth", 12)),
        "use_poisson": bool(emva.get("use_poisson_shot_noise", True)),
    }


# =====================================================================
# EMVA 1288 analysis
# =====================================================================
def _temporal(stack: np.ndarray) -> tuple[float, float]:
    s = np.asarray(stack, dtype=np.float64)
    return float(s.mean()), float(s.var(axis=0, ddof=1).mean())


def _nearest(entries: list[tuple[float, np.ndarray]], t: float) -> tuple[float, np.ndarray]:
    return min(entries, key=lambda e: abs(e[0] - t))


def analyse_emva(
    darks: list[tuple[float, np.ndarray]],
    flats: list[tuple[float, float | None, np.ndarray]],
) -> dict:
    """EMVA 1288 photon-transfer analysis.

    *darks*: ``(exposure_s, stack)``; *flats*: ``(exposure_s, relative_exposure,
    stack)``; stacks are ``(L, H, W)`` DN from a single colour plane.

    * K from the slope of ``sigma2_y - sigma2_y.dark`` vs ``mu_y - mu_y.dark``
      over 0..70 % of saturation (EMVA 1288 photon transfer method);
    * saturation capacity at the mean where the temporal variance peaks;
    * read noise ``sqrt(sigma2_y.dark - 1/12) / K`` at the shortest exposure;
    * dark current from the slope of the dark mean vs exposure time;
    * DSNU1288 / PRNU1288 with the residual-temporal-noise correction
      (tools/emva_theory.emva1288_dsnu / emva1288_prnu).
    """
    if not darks or not flats:
        raise ValueError("EMVA analysis needs at least one dark and one flat stack")
    darks = sorted(darks, key=lambda d: d[0])
    dark_stats = [(t, *_temporal(s)) for t, s in darks]
    points = []
    for idx, (t, rel, s) in enumerate(flats):
        mu, var = _temporal(s)
        _, dmu, dvar = min(dark_stats, key=lambda d: abs(d[0] - t))
        points.append(
            {"exposure_s": t, "relative_exposure": rel, "mu_dn": mu - dmu, "var_dn2": var - dvar, "stack": idx}
        )
    points.sort(key=lambda p: p["mu_dn"])
    mu = np.array([p["mu_dn"] for p in points])
    var = np.array([p["var_dn2"] for p in points])

    i_sat = int(np.argmax(var))
    saturated = i_sat < len(points) - 1
    mu_sat = float(mu[i_sat])
    sel = (mu > 0) & (mu <= K_FIT_MAX_FRACTION_OF_SAT * mu_sat)
    if sel.sum() < 2:
        raise ValueError("need >= 2 flat levels between 0 and 70 % of saturation to fit K")
    slope, intercept = np.polyfit(mu[sel], var[sel], 1)
    k_e_per_dn = 1.0 / float(slope)

    t0, dmu0, dvar0 = dark_stats[0]
    read_e = math.sqrt(max(dvar0 - QUANTISATION_VAR_DN2, 0.0)) * k_e_per_dn
    if len(dark_stats) >= 2 and dark_stats[-1][0] > dark_stats[0][0]:
        ts = np.array([d[0] for d in dark_stats])
        ms = np.array([d[1] for d in dark_stats])
        d_slope, d_icpt = np.polyfit(ts, ms, 1)
        dark_current = float(d_slope) * k_e_per_dn
        black = float(d_icpt)
    else:
        dark_current, black = None, dmu0

    dsnu = et.emva1288_dsnu(darks[0][1], k_e_per_dn)
    unsat = [i for i in range(len(points)) if i < i_sat] or [0]
    i50 = min(unsat, key=lambda i: abs(mu[i] - 0.5 * mu_sat))
    t50 = points[i50]["exposure_s"]
    flat50 = flats[points[i50]["stack"]][2]
    prnu = et.emva1288_prnu(_nearest(darks, t50)[1], flat50)
    return {
        "K_e_per_DN": k_e_per_dn,
        "K_fit_intercept_dn2": float(intercept),
        "read_noise_e": read_e,
        "dsnu_e": dsnu.dsnu_e,
        "prnu_fraction": prnu.prnu_fraction,
        "dark_current_e_per_s": dark_current,
        "full_well_e": mu_sat * k_e_per_dn if saturated else None,
        "saturation_reached": saturated,
        "black_level_DN": black,
        "ptc": points,
        "n_frames": int(darks[0][1].shape[0]),
        "plane_shape": list(darks[0][1].shape[1:]),
    }


def simulate_emva_captures(
    rec: dict,
    darks: list[tuple[float, np.ndarray]],
    flats: list[tuple[float, float | None, np.ndarray]],
    measured: dict,
    seed: int = 0,
) -> tuple[list, list]:
    """Recipe-model stacks matching the measured exposures, levels and sizes.

    Flat signal is reproduced from ``relative_exposure`` (photons scale with it)
    using the photon scale implied by the unsaturated measured points and the
    recipe K; without it each level is matched to the measured mean (saturated
    levels then cannot be reproduced). The forward model is
    tools/emva_theory.simulate_uniform_stack -- the EMVA picture apply_emva_noise
    implements -- followed by rounding and clipping to the ADC range.
    """
    shape = darks[0][1].shape[1:]
    rng = np.random.default_rng(seed)
    prnu_map = 1.0 + rng.normal(0.0, rec["prnu_fraction"], size=shape)
    dsnu_map = rng.normal(0.0, rec["dsnu_e"], size=shape)
    max_dn = float(2 ** rec["bit_depth"] - 1)
    k = rec["K_e_per_DN"]

    def stack(mu_e: float, t: float, n: int, s: int) -> np.ndarray:
        dn = et.simulate_uniform_stack(
            mu_e=mu_e,
            n_frames=n,
            prnu_map=prnu_map,
            dsnu_map=dsnu_map,
            dark_mean_e=rec["dark_current_e_per_s"] * t,
            sigma_d_e=rec["read_noise_e"],
            K_e_per_DN=k,
            black_level_DN=rec["black_level_DN"],
            full_well_e=rec["full_well_e"],
            use_poisson=rec["use_poisson"],
            seed=s,
        )
        return np.clip(np.rint(dn), 0.0, max_dn)

    pts = measured["ptc"]
    mu_sat = max(p["mu_dn"] for p in pts if p["var_dn2"] == max(q["var_dn2"] for q in pts))
    ref = [p for p in pts if p["relative_exposure"] and 0 < p["mu_dn"] <= K_FIT_MAX_FRACTION_OF_SAT * mu_sat]
    photon_scale = float(np.median([p["mu_dn"] * k / p["relative_exposure"] for p in ref])) if ref else None

    sim_darks = [(t, stack(0.0, t, s.shape[0], seed + 1 + i)) for i, (t, s) in enumerate(darks)]
    sim_flats = []
    for i, (t, rel, s) in enumerate(flats):
        if rel is not None and photon_scale is not None:
            mu_e = photon_scale * float(rel)
        else:
            mu_e = max(_temporal(s)[0] - _nearest(darks, t)[1].mean(), 0.0) * k
        sim_flats.append((t, rel, stack(mu_e, t, s.shape[0], seed + 100 + i)))
    return sim_darks, sim_flats


EMVA_KEYS = ("K_e_per_DN", "read_noise_e", "dsnu_e", "prnu_fraction", "dark_current_e_per_s", "full_well_e")


def _rel(a: float | None, b: float | None) -> float | None:
    if a is None or b is None or b == 0:
        return None
    return 100.0 * (float(a) / float(b) - 1.0)


def emva_section(capture: Capture, rec: dict, seed: int) -> dict:
    cfg = capture.cfg["emva"]
    colour = str(cfg.get("plane", "G"))
    roi = cfg.get("roi")
    darks = [(float(e["exposure_s"]), capture.stack(e, roi, colour)) for e in cfg["darks"]]
    flats = [(float(e["exposure_s"]), e.get("relative_exposure"), capture.stack(e, roi, colour)) for e in cfg["flats"]]
    measured = analyse_emva(darks, flats)
    sim_d, sim_f = simulate_emva_captures(rec, darks, flats, measured, seed)
    simulated = analyse_emva(sim_d, sim_f)
    table = {
        k: {
            "measured": measured[k],
            "recipe": rec[k],
            "simulated": simulated[k],
            "measured_vs_recipe_pct": _rel(measured[k], rec[k]),
            "measured_vs_simulated_pct": _rel(measured[k], simulated[k]),
        }
        for k in (*EMVA_KEYS, "black_level_DN")
    }
    return {"plane": colour, "parameters": table, "measured": measured, "simulated": simulated}


# =====================================================================
# Running the production sensor chain (apply_emva_noise.py)
# =====================================================================
def run_sensor_chain(
    recipe: Path, electrons_rgb: np.ndarray, integration_time_s: float, seed: int, workdir: Path
) -> np.ndarray:
    """Push an ``(H, W, 3)`` electron image through tools/apply_emva_noise.py; return raw DN."""
    workdir.mkdir(parents=True, exist_ok=True)
    npz = workdir / f"electrons_{seed}.npz"
    raw = workdir / f"raw_{seed}.raw16"
    np.savez(npz, electrons_rgb=np.asarray(electrons_rgb, dtype=np.float32))
    cmd = [
        sys.executable,
        str(TOOLS / "apply_emva_noise.py"),
        "--repo-root",
        str(REPO),
        "--camera-model-config",
        str(recipe),
        "--electrons-npz",
        str(npz),
        "--seed",
        str(int(seed)),
        "--integration-time-s",
        repr(float(integration_time_s)),
        "--exposure-scale",
        "1.0",
        "--raw-out",
        str(raw),
        "--preview-white-balance-enabled",
        "false",
        "--preview-color-correction-enabled",
        "false",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"apply_emva_noise failed:\n{proc.stdout}\n{proc.stderr}")
    h, w = electrons_rgb.shape[:2]
    return read_raw(raw, {"format": "raw16", "height": h, "width": w})[0]


# =====================================================================
# ColorChecker
# =====================================================================
def patch_rois(cfg: dict) -> list[list[int]]:
    """24 patch ROIs, row-major from patch 1 (dark skin) to 24 (black)."""
    if "patch_rois" in cfg:
        rois = [list(map(int, r)) for r in cfg["patch_rois"]]
    else:
        g = cfg["grid"]
        (x0, y0), (x1, y1) = g["first_patch_centre_px"], g["last_patch_centre_px"]
        h = int(g.get("patch_half_size_px", 8))
        rois = []
        for i in range(4):
            for j in range(6):
                cx = x0 + (x1 - x0) * j / 5.0
                cy = y0 + (y1 - y0) * i / 3.0
                rois.append([round(cx - h), round(cy - h), round(cx + h), round(cy + h)])
    if len(rois) != cs.COLORCHECKER_PATCHES:
        raise ValueError(f"expected {cs.COLORCHECKER_PATCHES} patch ROIs, got {len(rois)}")
    return rois


def patch_means_dn(img: np.ndarray, pattern: str | None, rois: list, black: float) -> np.ndarray:
    return np.array([[colour_mean(crop(img, r), pattern, c) - black for c in "RGB"] for r in rois])


def spectral_patch_electrons(model: dict, illuminant: str) -> tuple[np.ndarray, np.ndarray]:
    """Relative camera electrons ``(24, 3)`` and reference XYZ (Y_white = 1)."""
    wl = SPECTRAL_GRID_NM
    chart = cs.load_colorchecker(REPO, wl)
    _, spd = cs.load_illuminant(REPO, illuminant, wl)
    q = model["sensor"]["quantum_efficiency"]
    qe = cs.load_qe_rgb(
        REPO, {"red": q["red_csv"], "green": q["green_csv"], "blue": q["blue_csv"], "ircf": q.get("ircf_csv")}, wl
    )
    rgb = cs.camera_rgb_from_spectra(wl, chart.reflectance, spd, qe, normalise=False)
    xyz = cs.xyz_from_spectra(wl, chart.reflectance, spd)
    return rgb, xyz


def chart_electron_image(patch_e: np.ndarray, patch_px: int) -> np.ndarray:
    img = np.zeros((4 * patch_px, 6 * patch_px, 3), dtype=np.float64)
    for n in range(24):
        i, j = divmod(n, 6)
        img[i * patch_px : (i + 1) * patch_px, j * patch_px : (j + 1) * patch_px] = patch_e[n]
    return img


def chart_grid_cfg(patch_px: int) -> dict:
    return {
        "first_patch_centre_px": [patch_px / 2.0, patch_px / 2.0],
        "last_patch_centre_px": [5.5 * patch_px, 3.5 * patch_px],
        "patch_half_size_px": patch_px // 4,
    }


def colorchecker_section(
    capture: Capture, recipe: Path, model: dict, rec: dict, emva: dict | None, seed: int, workdir: Path
) -> dict:
    """Per-patch electrons and colour error, measured vs simulated.

    The simulated chart is the recipe's QE x illuminant x reflectance spectra,
    scaled so the white patch's green signal equals the measured one (the
    absolute scene illuminance is not part of the capture), pushed through the
    production sensor chain. Colour error: one 3x3 matrix fitted (least squares)
    from simulated camera RGB to reference XYZ is applied to both, and CIEDE2000
    is computed between them, so it measures only the spectral-response mismatch.
    """
    cfg = capture.cfg["colorchecker"]
    black = emva["measured"]["black_level_DN"] if emva else capture.raw.get("black_level_DN", rec["black_level_DN"])
    img, meta = read_raw(capture.root / cfg["file"], capture.fmt(cfg))
    black = meta.get("black_level_DN", black)
    meas_dn = patch_means_dn(img, capture.pattern, patch_rois(cfg), black)
    k_meas = emva["measured"]["K_e_per_DN"] if emva else rec["K_e_per_DN"]

    rel_e, xyz_ref = spectral_patch_electrons(model, str(cfg.get("illuminant", "D65")))
    scale = meas_dn[WHITE_PATCH, 1] * rec["K_e_per_DN"] / rel_e[WHITE_PATCH, 1]
    patch_px = int(cfg.get("simulated_patch_px", 24))
    sim_raw = run_sensor_chain(
        recipe, chart_electron_image(rel_e * scale, patch_px), float(cfg.get("exposure_s", 0.01)), seed, workdir
    )
    sim_dn = patch_means_dn(
        sim_raw,
        model["cfa"].get("pattern") if model["cfa"].get("enabled") else None,
        patch_rois({"grid": chart_grid_cfg(patch_px)}),
        rec["black_level_DN"],
    )

    meas_n = meas_dn / meas_dn[WHITE_PATCH, 1]
    sim_n = sim_dn / sim_dn[WHITE_PATCH, 1]
    ccm, *_ = np.linalg.lstsq(sim_n, xyz_ref, rcond=None)
    white = np.ones((1, SPECTRAL_GRID_NM.size))
    _, spd = cs.load_illuminant(REPO, str(cfg.get("illuminant", "D65")), SPECTRAL_GRID_NM)
    white_xyz = cs.xyz_from_spectra(SPECTRAL_GRID_NM, white, spd)[0]
    lab_meas = cs.xyz_to_lab(meas_n @ ccm, white_xyz)
    lab_sim = cs.xyz_to_lab(sim_n @ ccm, white_xyz)
    de = cs.delta_e_2000(lab_meas, lab_sim)
    rel_err = 100.0 * (meas_n / np.maximum(sim_n, 1e-12) - 1.0)
    chroma_meas = np.stack([meas_n[:, 0] / meas_n[:, 1], meas_n[:, 2] / meas_n[:, 1]], axis=1)
    chroma_sim = np.stack([sim_n[:, 0] / sim_n[:, 1], sim_n[:, 2] / sim_n[:, 1]], axis=1)
    chart = cs.load_colorchecker(REPO, SPECTRAL_GRID_NM)
    patches = [
        {
            "index": i + 1,
            "name": chart.names[i],
            "measured_e_rgb": (meas_dn[i] * k_meas).tolist(),
            "simulated_e_rgb": (sim_dn[i] * rec["K_e_per_DN"]).tolist(),
            "white_normalised_error_pct_rgb": rel_err[i].tolist(),
            "rg_bg_ratio_error_pct": (100.0 * (chroma_meas[i] / chroma_sim[i] - 1.0)).tolist(),
            "delta_e_2000": float(de[i]),
        }
        for i in range(24)
    ]
    neutral = slice(18, 24)
    return {
        "illuminant": str(cfg.get("illuminant", "D65")),
        "black_level_DN_used": float(black),
        "white_scale_e": float(scale),
        "delta_e_2000_mean": float(np.mean(de)),
        "delta_e_2000_max": float(np.max(de)),
        "rms_white_normalised_error_pct": float(np.sqrt(np.mean(rel_err[:, [0, 2]] ** 2))),
        "neutral_channel_ratio_meas_over_sim": (meas_n[neutral].mean(0) / sim_n[neutral].mean(0)).tolist(),
        "patches": patches,
    }


# =====================================================================
# Slanted edge
# =====================================================================
def optics_mtf_2d(shape: tuple[int, int], model: dict, extra_sigma_px: float = 0.0) -> np.ndarray:
    """Recipe optics MTF on an FFT grid: diffraction at the working f-number
    (550 nm) times the recipe's post-PSF Gaussian when enabled, times an
    optional extra Gaussian blur. This is a lens-aberration-free model; supply
    ``slanted_edge.simulated_file`` (a pbrt render through the traced lens and
    apply_emva_noise) to compare against a full simulation instead."""
    fy = np.fft.fftfreq(shape[0])[:, None]
    fx = np.fft.fftfreq(shape[1])[None, :]
    fr = np.hypot(fx, fy)
    sensor, lens = model["sensor"], model.get("lens", {})
    n = effective_f_number(sensor, lens, tag="validate_against_capture")
    pitch = float(sensor.get("pixel_pitch_um", 1.4))
    h = sfr.diffraction_mtf(fr, n, 550.0, pitch)
    psf = lens.get("post_psf", {}) or {}
    sigma = float(psf.get("sigma_geometric_pixels", 0.0)) if psf.get("enabled") else 0.0
    sigma = math.hypot(sigma, float(extra_sigma_px))
    if sigma > 0:
        h = h * sfr.gaussian_mtf(fr, sigma)
    return h


def blur(img: np.ndarray, mtf2d_fn) -> np.ndarray:
    pad = 32
    p = np.pad(img, pad, mode="reflect")
    out = np.real(np.fft.ifft2(np.fft.fft2(p) * mtf2d_fn(p.shape)))
    return out[pad:-pad, pad:-pad]


def edge_plateaus(plane: np.ndarray) -> tuple[float, float]:
    fit = sfr.fit_edge(plane)
    rows, cols = np.mgrid[0 : plane.shape[0], 0 : plane.shape[1]].astype(float)
    d = (cols - fit.position(rows[:, 0])[:, None]) * fit.polarity
    m = max(4.0, plane.shape[1] / 6.0)
    return float(plane[d < -m].mean()), float(plane[d > m].mean())


def measure_edge(img: np.ndarray, pattern: str | None, colour: str, flatfield: bool) -> dict:
    plane = cfa_plane(img, pattern, colour)
    step = 2.0 if pattern else 1.0
    r = sfr.slanted_edge_sfr(plane, flatfield=flatfield)
    edge = sfr.fit_edge(plane)
    return {
        "angle_deg": r.angle_deg,
        "polarity": edge.polarity,
        "frequency_cy_per_px": (r.frequency_cy_per_px / step).tolist(),
        "mtf": r.mtf.tolist(),
        "mtf50_cy_per_px": r.mtf50_cy_per_px / step,
        "plane_nyquist_cy_per_px": 0.5 / step,
    }


def synthetic_edge_unit(h: int, w: int, angle_deg: float, polarity: int) -> np.ndarray:
    e = sfr.synthetic_slanted_edge(h, w, angle_deg, dark=0.0, bright=1.0)
    if sfr.fit_edge(e).polarity != polarity:
        e = sfr.synthetic_slanted_edge(h, w, -angle_deg, dark=0.0, bright=1.0)[:, ::-1]
    return e


def slanted_edge_section(
    capture: Capture, recipe: Path, model: dict, rec: dict, emva: dict | None, seed: int, workdir: Path
) -> dict:
    cfg = capture.cfg["slanted_edge"]
    colour = str(cfg.get("plane", "G"))
    flat = bool(cfg.get("flatfield", False))
    black = emva["measured"]["black_level_DN"] if emva else capture.raw.get("black_level_DN", rec["black_level_DN"])
    img, meta = read_raw(capture.root / cfg["file"], capture.fmt(cfg))
    img = crop(img, cfg.get("roi")) - meta.get("black_level_DN", black)
    measured = measure_edge(img, capture.pattern, colour, flat)

    sim_pattern = model["cfa"].get("pattern") if model["cfa"].get("enabled") else None
    if cfg.get("simulated_file"):
        sim_img, _ = read_raw(capture.root / cfg["simulated_file"], capture.fmt(cfg))
        sim_img = crop(sim_img, cfg.get("roi")) - rec["black_level_DN"]
        source = "simulated_file"
    else:
        unit = synthetic_edge_unit(img.shape[0], img.shape[1], measured["angle_deg"], measured["polarity"])
        unit = blur(unit, lambda s: optics_mtf_2d(s, model))
        k = rec["K_e_per_DN"]
        levels = [edge_plateaus(cfa_plane(img, capture.pattern, c)) for c in "RGB"]
        e = np.stack([(lo + (hi - lo) * unit) * k for lo, hi in levels], axis=-1)
        sim_img = run_sensor_chain(recipe, np.clip(e, 0, None), float(cfg.get("exposure_s", 0.01)), seed, workdir)
        sim_img = sim_img - rec["black_level_DN"]
        source = "recipe_optics_model"
    simulated = measure_edge(sim_img, sim_pattern, colour, flat)
    f = np.asarray(measured["frequency_cy_per_px"])
    keep = f <= measured["plane_nyquist_cy_per_px"]
    sim_on = np.interp(f[keep], simulated["frequency_cy_per_px"], simulated["mtf"])
    pitch = float(model["sensor"].get("pixel_pitch_um", 1.4))
    out = {
        "plane": colour,
        "simulation": source,
        "measured": measured,
        "simulated": simulated,
        "mtf50_measured_cy_per_px": measured["mtf50_cy_per_px"],
        "mtf50_simulated_cy_per_px": simulated["mtf50_cy_per_px"],
        "mtf50_measured_lp_per_mm": sfr.cycles_per_mm(measured["mtf50_cy_per_px"], pitch),
        "mtf50_simulated_lp_per_mm": sfr.cycles_per_mm(simulated["mtf50_cy_per_px"], pitch),
        "mtf50_measured_vs_simulated_pct": _rel(measured["mtf50_cy_per_px"], simulated["mtf50_cy_per_px"]),
        "mtf_rms_difference_to_plane_nyquist": float(
            np.sqrt(np.mean((np.asarray(measured["mtf"])[keep] - sim_on) ** 2))
        ),
    }
    for fq in (0.1, 0.2):
        out[f"mtf_at_{fq}_cy_per_px"] = {
            "measured": float(np.interp(fq, f, measured["mtf"])),
            "simulated": float(np.interp(fq, simulated["frequency_cy_per_px"], simulated["mtf"])),
        }
    return out


# =====================================================================
# Report, plots, recipe re-fit
# =====================================================================
def _fmt(v: object) -> str:
    if v is None:
        return "n/a"
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def markdown_report(report: dict) -> str:
    lines = [f"# Capture validation: {report['recipe']}", ""]
    if report.get("synthetic"):
        lines += ["**Synthetic capture (simulator round trip) -- not a real-camera validation.**", ""]
    if "emva" in report:
        lines += [
            f"## EMVA 1288 ({report['emva']['plane']} plane)",
            "",
            "| parameter | measured | recipe | simulated | meas vs recipe % | meas vs sim % |",
            "|---|---|---|---|---|---|",
        ]
        for k, r in report["emva"]["parameters"].items():
            vals = [r["measured"], r["recipe"], r["simulated"], r["measured_vs_recipe_pct"]]
            lines.append(
                f"| {k} | " + " | ".join(_fmt(v) for v in vals) + f" | {_fmt(r['measured_vs_simulated_pct'])} |"
            )
        lines.append("")
    if "colorchecker" in report:
        c = report["colorchecker"]
        lines += [
            "## ColorChecker",
            "",
            f"CIEDE2000 measured vs simulated: mean {c['delta_e_2000_mean']:.2f}, max {c['delta_e_2000_max']:.2f}; "
            f"RMS white-normalised R/B error {c['rms_white_normalised_error_pct']:.2f} %",
            "",
            "| # | patch | meas e- (R,G,B) | sim e- (R,G,B) | err % (R,G,B) | dE00 |",
            "|---|---|---|---|---|---|",
        ]
        for pt in c["patches"]:
            fm = lambda a, f: ", ".join(f.format(v) for v in a)  # noqa: E731
            lines.append(
                f"| {pt['index']} | {pt['name']} | {fm(pt['measured_e_rgb'], '{:.0f}')} | "
                f"{fm(pt['simulated_e_rgb'], '{:.0f}')} | {fm(pt['white_normalised_error_pct_rgb'], '{:+.1f}')} | "
                f"{pt['delta_e_2000']:.2f} |"
            )
        lines.append("")
    if "slanted_edge" in report:
        e = report["slanted_edge"]
        lines += [
            f"## Slanted edge ({e['plane']} plane, simulation: {e['simulation']})",
            "",
            f"- edge angle: measured {e['measured']['angle_deg']:.3f} deg",
            f"- MTF50: measured {e['mtf50_measured_cy_per_px']:.4f} cy/px ({e['mtf50_measured_lp_per_mm']:.1f} lp/mm), "
            f"simulated {e['mtf50_simulated_cy_per_px']:.4f} cy/px ({e['mtf50_simulated_lp_per_mm']:.1f} lp/mm), "
            f"{_fmt(e['mtf50_measured_vs_simulated_pct'])} %",
            f"- RMS MTF difference up to plane Nyquist: {e['mtf_rms_difference_to_plane_nyquist']:.4f}",
            "",
        ]
    return "\n".join(lines)


def plot_report(report: dict, path: Path) -> None:
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    fig, axes = plt.subplots(1, 3, figsize=(11, 3.2))
    if "emva" in report:
        for key, style in (("measured", "o"), ("simulated", "x")):
            pts = report["emva"][key]["ptc"]
            axes[0].plot([p["mu_dn"] for p in pts], [p["var_dn2"] for p in pts], style, ms=4, label=key)
        k = report["emva"]["parameters"]["K_e_per_DN"]["recipe"]
        mu = np.linspace(0, max(p["mu_dn"] for p in report["emva"]["measured"]["ptc"]), 50)
        axes[0].plot(mu, mu / k, "k:", lw=1, label="recipe K")
        axes[0].set_xlabel("mean - dark [DN]")
        axes[0].set_ylabel("temporal variance - dark [DN$^2$]")
        axes[0].set_title("Photon transfer", fontsize=9)
        axes[0].legend(fontsize=7)
    if "colorchecker" in report:
        pts = report["colorchecker"]["patches"]
        err = np.array([p["white_normalised_error_pct_rgb"] for p in pts])
        x = np.arange(1, 25)
        for i, (c, col) in enumerate(zip("RGB", ("tab:red", "tab:green", "tab:blue"))):
            axes[1].bar(x + (i - 1) * 0.27, err[:, i], width=0.27, color=col, label=c)
        ax2 = axes[1].twinx()
        ax2.plot(x, [p["delta_e_2000"] for p in pts], "k.-", lw=0.8)
        ax2.set_ylabel("$\\Delta E_{00}$")
        axes[1].set_xlabel("patch")
        axes[1].set_ylabel("meas/sim - 1 [%]")
        axes[1].set_title("ColorChecker (white-normalised)", fontsize=9)
        axes[1].legend(fontsize=7)
    if "slanted_edge" in report:
        e = report["slanted_edge"]
        for key in ("measured", "simulated"):
            f = np.asarray(e[key]["frequency_cy_per_px"])
            sel = f <= 0.5
            axes[2].plot(f[sel], np.asarray(e[key]["mtf"])[sel], label=f"{key} (MTF50 {e[key]['mtf50_cy_per_px']:.3f})")
        axes[2].axvline(e["measured"]["plane_nyquist_cy_per_px"], color="0.5", ls=":", lw=1)
        axes[2].set_xlabel("frequency [cy/px]")
        axes[2].set_ylabel("MTF")
        axes[2].set_ylim(0, 1.05)
        axes[2].set_title("Slanted-edge SFR", fontsize=9)
        axes[2].legend(fontsize=7)
    for ax in axes:
        ax.tick_params(labelsize=7)
        ax.grid(True, lw=0.3, alpha=0.5)
    fig.tight_layout()
    fig.savefig(path, dpi=130)
    plt.close(fig)


def refit_model(model: dict, report: dict, recipe: Path) -> dict:
    """Full in-file camera model with the measured EMVA parameters substituted.

    Loadable directly with ``--camera-model-config`` (load_camera_model accepts
    a full model); see docs/REAL_CAMERA_VALIDATION.md for turning it into a
    composed sensor model + recipe.
    """
    out = copy.deepcopy(model)
    out.pop("resolved_from", None)
    emva = out["noise"]["emva"]
    adc = out["noise"]["adc"]
    m = report["emva"]["measured"]
    gain = float(emva.get("iso_gain_factor", 1.0))
    emva["overall_system_gain_K_e_per_DN"] = float(m["K_e_per_DN"]) * gain
    emva["sigma_d_e"] = float(m["read_noise_e"])
    emva["sigma_amp_e"] = 0.0
    emva["dsnu_std_e"] = float(m["dsnu_e"])
    emva["dsnu_rate_std_fraction"] = 0.0
    emva["prnu_std_fraction"] = float(m["prnu_fraction"])
    for key in ("prnu_std_fraction_r", "prnu_std_fraction_g", "prnu_std_fraction_b"):
        emva.pop(key, None)
    emva["black_level_DN"] = float(m["black_level_DN"])
    if m["dark_current_e_per_s"] is not None:
        t_cap = report.get("temperature_c")
        if t_cap is not None:
            emva["temperature_c"] = float(t_cap)
            emva["dark_current_reference_temp_c"] = float(t_cap)
        emva["dark_current_e_per_s"] = max(float(m["dark_current_e_per_s"]), 0.0)
    if m["full_well_e"] is not None:
        adc["full_well_e"] = float(m["full_well_e"]) * gain
    src = out.setdefault("source", {})
    src["calibration_tier"] = "measured_emva1288"
    src["refit_from_recipe"] = str(recipe)
    return out


def validate(capture_path: Path, out_dir: Path, recipe_override: Path | None = None, seed: int = 0) -> dict:
    capture = load_capture(capture_path)
    recipe = resolve_recipe(capture, recipe_override)
    model = load_camera_model(recipe)
    rec = recipe_emva(model, capture.raw.get("temperature_c"))
    report: dict = {
        "recipe": str(recipe),
        "capture": str(Path(capture_path).resolve()),
        "synthetic": bool(capture.cfg.get("synthetic", False)),
        "temperature_c": capture.raw.get("temperature_c"),
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        emva = None
        if capture.cfg.get("emva"):
            emva = emva_section(capture, rec, seed)
            report["emva"] = emva
        if capture.cfg.get("colorchecker"):
            report["colorchecker"] = colorchecker_section(capture, recipe, model, rec, emva, seed + 1000, work)
        if capture.cfg.get("slanted_edge"):
            report["slanted_edge"] = slanted_edge_section(capture, recipe, model, rec, emva, seed + 2000, work)
    (out_dir / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    (out_dir / "report.md").write_text(markdown_report(report) + "\n")
    return report


# =====================================================================
# Synthetic round-trip capture
# =====================================================================
FLAT_FRACTIONS = (0.02, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.98, 1.0, 1.02, 1.05, 1.1)


def synthesize(
    recipe: Path,
    out_dir: Path,
    *,
    tile: tuple[int, int] = (64, 64),
    frames: int = 4,
    dark_exposures: tuple[float, ...] = (0.01, 10.0, 40.0),
    flat_exposure: float = 0.01,
    edge_extra_blur_px: float = 0.0,
    edge_angle_deg: float = 5.0,
    illuminant: str = "D65",
    seed: int = 0,
) -> Path:
    """Write a capture set produced by apply_emva_noise from *recipe*.

    Flat levels are tiled side by side in one frame (one simulator call per
    frame) and then cut into separate per-level files; the first tile is
    unlit and doubles as the dark stack at the flat exposure.
    """
    recipe = Path(recipe).resolve()
    model = load_camera_model(recipe)
    rec = recipe_emva(model)
    out_dir = Path(out_dir)
    (out_dir / "ptc").mkdir(parents=True, exist_ok=True)
    pattern = model["cfa"].get("pattern") if model["cfa"].get("enabled") else None
    th, tw = tile
    fw = rec["full_well_e"]
    levels = (0.0, *FLAT_FRACTIONS)
    work = out_dir / "_work"

    def write(name: str, raw: np.ndarray) -> str:
        np.rint(raw).astype("<u2").tofile(out_dir / name)
        return name

    flat_img = np.concatenate([np.full((th, tw, 3), f * fw) for f in levels], axis=1)
    darks: dict[float, list[str]] = {t: [] for t in dark_exposures}
    flats: list[list[str]] = [[] for _ in FLAT_FRACTIONS]
    for k in range(frames):
        raw = run_sensor_chain(recipe, flat_img, flat_exposure, seed + 10 * k, work)
        for i in range(len(levels)):
            tile_raw = raw[:, i * tw : (i + 1) * tw]
            if i == 0:
                if flat_exposure in darks:
                    darks[flat_exposure].append(write(f"ptc/dark_t{flat_exposure:g}_f{k}.raw16", tile_raw))
            else:
                flats[i - 1].append(write(f"ptc/flat_l{i:02d}_f{k}.raw16", tile_raw))
        for t in dark_exposures:
            if t == flat_exposure:
                continue
            raw_d = run_sensor_chain(recipe, np.zeros((th, tw, 3)), t, seed + 10 * k + 1 + len(darks[t]), work)
            darks[t].append(write(f"ptc/dark_t{t:g}_f{k}.raw16", raw_d))

    patch_px = 24
    rel_e, _ = spectral_patch_electrons(model, illuminant)
    chart = chart_electron_image(rel_e * (0.6 * fw / rel_e[WHITE_PATCH, 1]), patch_px)
    write("colorchecker.raw16", run_sensor_chain(recipe, chart, flat_exposure, seed + 7, work))

    eh, ew = 192, 128
    unit = synthetic_edge_unit(eh, ew, edge_angle_deg, 1)
    unit = blur(unit, lambda s: optics_mtf_2d(s, model, edge_extra_blur_px))
    edge_e = np.repeat(((0.1 + 0.6 * unit) * fw)[..., None], 3, axis=-1)
    write("slanted_edge.raw16", run_sensor_chain(recipe, edge_e, flat_exposure, seed + 8, work))

    for f in work.glob("*"):
        if f.is_file():
            f.unlink()
    for d in sorted(work.glob("**/*"), reverse=True):
        if d.is_file():
            d.unlink()
        else:
            d.rmdir()
    work.rmdir()

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "synthetic": True,
        "camera_recipe": str(recipe),
        "raw": {
            "format": "raw16",
            "height": th,
            "width": tw,
            "cfa_pattern": pattern,
            "bit_depth": rec["bit_depth"],
            "temperature_c": float(model["noise"]["emva"].get("temperature_c", 20.0)),
        },
        "emva": {
            "plane": "G",
            "darks": [{"exposure_s": t, "frames": f"ptc/dark_t{t:g}_f*.raw16"} for t in dark_exposures],
            "flats": [
                {"exposure_s": flat_exposure, "relative_exposure": f, "frames": f"ptc/flat_l{i + 1:02d}_f*.raw16"}
                for i, f in enumerate(FLAT_FRACTIONS)
            ],
        },
        "colorchecker": {
            "file": "colorchecker.raw16",
            "height": 4 * patch_px,
            "width": 6 * patch_px,
            "exposure_s": flat_exposure,
            "illuminant": illuminant,
            "grid": chart_grid_cfg(patch_px),
        },
        "slanted_edge": {
            "file": "slanted_edge.raw16",
            "height": eh,
            "width": ew,
            "exposure_s": flat_exposure,
            "plane": "G",
            "synthetic_extra_blur_px": edge_extra_blur_px,
        },
    }
    path = out_dir / "capture.yaml"
    path.write_text(yaml.safe_dump(manifest, sort_keys=False))
    return path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    v = sub.add_parser("validate", help="compare captures with the recipe")
    v.add_argument("--capture", type=Path, required=True, help="capture.yaml")
    v.add_argument("--recipe", type=Path, default=None, help="override camera_recipe from capture.yaml")
    v.add_argument("--out-dir", type=Path, required=True)
    v.add_argument("--plot", action="store_true", help="write validation.png")
    v.add_argument("--refit-out", type=Path, default=None, help="write a camera model with measured EMVA values")
    v.add_argument("--seed", type=int, default=0)
    s = sub.add_parser("synthesize", help="simulator-generated capture set for round-trip tests")
    s.add_argument("--recipe", type=Path, required=True)
    s.add_argument("--out-dir", type=Path, required=True)
    s.add_argument("--frames", type=int, default=4)
    s.add_argument("--edge-extra-blur-px", type=float, default=0.0)
    s.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    if args.cmd == "synthesize":
        print(
            f"Wrote {synthesize(args.recipe, args.out_dir, frames=args.frames, edge_extra_blur_px=args.edge_extra_blur_px, seed=args.seed)}"
        )
        return
    report = validate(args.capture, args.out_dir, args.recipe, args.seed)
    if args.plot:
        plot_report(report, args.out_dir / "validation.png")
    if args.refit_out is not None:
        if "emva" not in report:
            raise SystemExit("--refit-out needs an emva section in the capture")
        model = load_camera_model(Path(report["recipe"]))
        args.refit_out.parent.mkdir(parents=True, exist_ok=True)
        args.refit_out.write_text(yaml.safe_dump(refit_model(model, report, Path(report["recipe"])), sort_keys=False))
        print(f"Wrote {args.refit_out}")
    print((args.out_dir / "report.md").read_text())


if __name__ == "__main__":
    main()
